apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: {{ .Values.metrics.name }}
    app.kubernetes.io/version: 2.3.0
  name: {{ .Values.metrics.name }}
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.metrics.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: {{ .Values.metrics.name }}
        app.kubernetes.io/version: 2.3.0
    spec:
      automountServiceAccountToken: true
      containers:
      - image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.metrics.config.httpMetricPort }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: {{ .Values.metrics.name }}
        ports:
        - containerPort: {{ .Values.metrics.config.httpMetricPort }}
          name: http-metrics
        - containerPort: {{ .Values.metrics.config.telemetryPort }}
          name: telemetry
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.metrics.config.telemetryPort }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 65534
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: {{ .Values.metrics.name }}
