apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.arangodb.name }}-secret 
  namespace: jalapeno 
  labels:
    app.kubernetes.io/instance: jalapeno
    app.kubernetes.io/name: {{ .Values.arangodb.name }}
type: Opaque
data:
  root-user-password: {{ ternary (randAlphaNum 10) .Values.arangodb.auth.admin.password (empty .Values.arangodb.auth.admin.password) | b64enc | quote }}
