apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.arangodb.name }}
  namespace: jalapeno
  labels: 
    app.kubernetes.io/component: {{ .Values.arangodb.name }}
    app.kubernetes.io/instance: jalapeno
    app.kubernetes.io/name: {{ .Values.arangodb.name }}
spec:
  type: {{ .Values.arangodb.service.type }}
  clusterIP: 10.43.83.183
  clusterIPs:
  - 10.43.83.183
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  ports:
    - port: 8086
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.arangodb.service.nodePort }}
  selector: 
    app.kubernetes.io/component: {{ .Values.arangodb.name }}
    app.kubernetes.io/instance: jalapeno
    app.kubernetes.io/name: {{ .Values.arangodb.name }}
