apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.name }}
  namespace: jalapeno
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "{{ .Values.grafana.service.port }}"
spec:
  ports:
  - port: {{ .Values.grafana.service.port }}
    protocol: TCP
    targetPort: {{ .Values.grafana.service.port }}
    nodePort: {{ .Values.grafana.service.nodePort }}
    name: http-grafana
  selector:
    app.kubernetes.io/component: {{ .Values.grafana.name }}
    app.kubernetes.io/instance: jalapeno
    app.kubernetes.io/name: {{ .Values.grafana.name }}
  sessionAffinity: None
  type: {{ .Values.grafana.service.type }}


