{{- if (not .Values.grafana.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.name }}-admin-secret
  namespace: jalapeno
  labels:
    app: {{ .Values.grafana.name }}
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: {{ ternary (randAlphaNum 10) .Values.grafana.admin.password (empty .Values.grafana.admin.password) | b64enc | quote }}
{{- end }}
