{
 "title": "Jalapeno Health Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_pod_status_ready, namespace)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_status_ready, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Deployments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (namespace) (kube_deployment_created{namespace=~\"jagw|jalapeno\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Totals Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_info{namespace=~\"jagw|jalapeno\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Total statefulsets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (statefulset,namespace) (kube_statefulset_replicas{namespace=~\"jagw|jalapeno\"})",
     "legendFormat": "{{namespace}}/{{statefulset}}"
    }
   ]
  },
  {
   "title": "Running pod ratio in jagw",
   "type": "stat",
   "description": "Here is the ratio num_running_pods/num_expected_pods  per deployment ",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(kube_deployment_status_replicas{namespace=\"jagw\"}/kube_deployment_spec_replicas{namespace=\"jagw\"})*100",
     "legendFormat": "{{deployment}} pods"
    }
   ]
  },
  {
   "title": "Running pod ratio in jalapeno",
   "type": "stat",
   "description": "Here is the ratio num_running_pods/num_expected_pods  per deployment ",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(kube_deployment_status_replicas{namespace=\"jalapeno\"}/kube_deployment_spec_replicas{namespace=\"jalapeno\"})*100",
     "legendFormat": "{{deployment}} pods"
    }
   ]
  },
  {
   "title": "jagw-readines-all-pods",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_ready{condition=\"true\",namespace=\"jagw\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "jalapeno-readines-all-pods",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_ready{condition=\"true\",namespace=\"jalapeno\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU time Consumption [jagw]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",namespace=\"jagw\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU time Consumption [jalapeno]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{job=\"kubernetes-cadvisor\",namespace=\"jalapeno\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MEM bytes Consumption [jagw]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"kubernetes-cadvisor\",namespace=\"jagw\",container!=\"\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MEM bytes Consumption [jalapeno]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"kubernetes-cadvisor\",namespace=\"jalapeno\",container!=\"\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "selected-pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "kube_pod_status_ready{namespace=~\"$Namespace\",pod=~\"$Pod\"}"
    }
   ]
  },
  {
   "title": "List of images",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=~\"jagw|jalapeno\"}",
     "legendFormat": "{{container}}:{{image}}"
    }
   ]
  }
 ]
}